INSERT INTO ACTUATION_REGION
(REGION_NAME, INCLUSION_DATE, LAST_UPDATE)
VALUES('sul', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO ACTUATION_REGION
(REGION_NAME, INCLUSION_DATE, LAST_UPDATE)
VALUES('sudeste', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO ACTUATION_REGION
(REGION_NAME, INCLUSION_DATE, LAST_UPDATE)
VALUES('norte', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO ACTUATION_REGION
(REGION_NAME, INCLUSION_DATE, LAST_UPDATE)
VALUES('nordeste', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO ACTUATION_REGION
(REGION_NAME, INCLUSION_DATE, LAST_UPDATE)
VALUES('centroeste', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());